# Generated by Django 5.2.6 on 2025-10-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='servicio_solicitado',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='e_commerce.servicio', verbose_name='Servicio Solicitado'),
            preserve_default=False,
        ),
    ]
