# Generated by Django 5.2.6 on 2025-10-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(max_length=500)),
                ('tecnica', models.CharField(max_length=100)),
                ('fecha_trabajo', models.DateField()),
            ],
        ),
    ]
