# Generated by Django 5.2.6 on 2025-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_contacto', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_trabajo', models.DateField()),
                ('imagen_antes', models.ImageField(upload_to='portafolio/')),
                ('imagen_despues', models.ImageField(upload_to='portafolio/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(max_length=500)),
                ('tecnica', models.CharField(max_length=100)),
                ('fecha_trabajo', models.DateField()),
            ],
        ),
    ]
