# Generated by Django 5.2.6 on 2025-10-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='portafolio/'),
        ),
    ]
