# Generated by Django 5.2.6 on 2025-10-28 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_servicio_remove_cita_servicio_solicitado_and_more'),
        ('portafolio', '0002_alter_portfolioitem_imagen_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
        migrations.AddField(
            model_name='itemportafolio',
            name='curso_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_commerce.curso'),
        ),
        migrations.AddField(
            model_name='itemportafolio',
            name='servicio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_commerce.servicio'),
        ),
        migrations.AddField(
            model_name='itemportafolio',
            name='tipo_item',
            field=models.CharField(choices=[('TRABAJO', 'Trabajo de Cliente'), ('CURSO', 'Curso Ejemplificado')], default='TRABAJO', max_length=10),
        ),
    ]
