# Generated by Django 5.2.6 on 2025-10-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
