# Generated by Django 5.2.6 on 2025-10-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('contenido_texto', models.TextField()),
                ('imagen_adjunta', models.ImageField(blank=True, null=True, upload_to='redes_sociales/')),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetricaReaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reaccion', models.CharField(max_length=50)),
                ('conteo', models.IntegerField()),
                ('publicacion_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redes_sociales.publicacionredsocial')),
            ],
        ),
    ]
